<?php
/**
 * @author MJMZ
 * This file will handle all the password recovery matters. User need to enter their username andkey-in a valid captcha image.
 * Then, the system automatically send an email address contained random password generated by the system itself.
 */ 
 include("lib/common.php");
   
 
//session_start();
	function runnum($column_name, $tblname) 
	{ 
		global $db_klas2;
		
		$run_start = "001";
		
		$sql_slct_max = "SELECT MAX($column_name) AS run_id FROM $tblname";
		$sql_slct = $db_klas2;
		$sql_slct->query($sql_slct_max);
		$sql_slct->next_record();

		if($sql_slct->num_rows($sql_slct_max)== 0 || $sql_slct->f("run_id")==NULL) 
		{
			$run_id = date("Ymd").$run_start;
		} 
		else 
		{
			$todate = date("Ymd");
			
			if($todate > substr($sql_slct->f("run_id"),0,8)) 
			{
				$run_id = $todate.$run_start;
			} 
			else 
			{
				$run_id = $sql_slct->f("run_id") + 1; 
			}
		}
		return $run_id;
	}

function random_pwd($len) //generate random pwd
	{
		$string = "";
		$chars = "ABCGHINOPQRSTUVabcdefJKLMghijklmnoWXYZpqrstuDEFvwxyz0123456789";
		for($i=0;$i<$len;$i++)
		$string.=substr($chars,rand(0,strlen($chars)),1);
		return $string;
	}

/*$_user_location	= 'public';
define('AT_INCLUDE_PATH', '../include/');
require (AT_INCLUDE_PATH.'vitals.inc.php');*/
$sqlAdmin = "SELECT const_value
FROM base_constant WHERE const_term = 'EMAIL_ADMIN'";

$resultsqlAdmin = $dbb->query($sqlAdmin);
$dbb->next_record();
$adminEmail=$dbb->f('const_value');

if($_POST['submit'] <> "") {

	$errormsg = array();
	if(empty($_POST['username'])) { $errormsg[]="<div class=\"error\"><span>Please insert username.</span></div>"; } else { $username = $_POST['username']; }
	if(empty($_POST['validation'])) 
	{ 
		$errormsg[]="<div class=\"error\"><span>Please insert validation code.</span></div>"; 
	} else if(md5($_POST['validation']) <> $_SESSION['validator']) {
		$errormsg[]="<div class=\"error\"><span>Validation code not match.</span></div>";
	}
	$varIsUser=true;
	if(empty($errormsg))
	{
		
		$sql_usename = "SELECT staff_id FROM user_acc WHERE staff_id='".$username."'";
		$result = $db->query($sql_usename);
		$row =  $db->num_rows($result);
		//echo $sql_username."<br>";
		if($row == 0) 
		{
			$varIsUser=false;
			//$errormsg[] = "<li class=\"messageboxerror\">Please enter a valid username</li>";
		} 
		else 
		{
			if (substr($username,0,2) == '07') { 
				
				$sql_email = "SELECT email,name FROM student
				WHERE matrix_no ='".$username."'";
				$dbConnStudent= $dbc1;
				$result2 =  $dbConnStudent->query($sql_email);;
				$row2 =  $dbConnStudent->fetchArray($result2);
				
			} else if (substr($username,0,3) == 'S07') {
				$sql_email = "SELECT email,name FROM new_employee
				WHERE empid ='".$username."'";
				$dbConnStudent= $dbc1;
				$result2 =  $dbConnStudent->query($sql_email);;
				$row2 =  $dbConnStudent->fetchArray($result2);
			
			} else if (substr($username,0,2) == '01'){ 
				$sql_email = "SELECT email,name FROM student
				WHERE matrix_no ='".$username."'";
				$dbConnStudent=$dbc; 
				$result2 =  $dbConnStudent->query($sql_email);;
				$row2 =  $dbConnStudent->fetchArray($result2);
				
			} else {
				
				$sql_email = "SELECT email,name FROM new_employee
				WHERE empid ='".$username."'";
				$dbConnStudent=$dbc; 
				$result2 =  $dbConnStudent->query($sql_email);;
				$row2 =  $dbConnStudent->fetchArray($result2);
			}
			
			
			if($row2['email'] == "") 
			{
				$errormsg[] = "<div class=\"error\">Your email doesn't exist . Please contact Information Technology and Innovation Centre(ITIC) @ ".$adminEmail."</div>";
			} 
			else if(!preg_match('/^[a-z0-9&\'\.\-_\+]+@[a-z0-9\-]+\.([a-z0-9\-]+\.)*+[a-z]{2}/is',$row2['email'])) 
			{ // check for valid email format
					$errormsg[] = "<div class=\"error\">Your email contains invalid characters. Please contact Information Technology and Innovation Centre(ITIC) @ ".$adminEmail."</div>";
			} 
			else 
			{
					$new_pwd = random_pwd(7); //generate random password 7 char length
					$generatePwd = md5($new_pwd);
					$clean_email = $row2['email']; // prepare valid email address.
					$userName = $row2['name']; // prepare valid email address.
					
					$credentialId = runnum('id','pg_credential');
					$sql2 = "INSERT INTO pg_credential
					(id, user_id, password, change_date)
					VALUES ('$credentialId', '".$username."', '".$generatePwd."', now())";
					
					$result_sq2 = $dbf->query($sql2);
					$dbf->next_record();
					
					$sql_upd = "UPDATE user_acc SET user_pass = '".$generatePwd."' WHERE staff_id = '".$username."'";
					$success = $db->query($sql_upd);
					//echo "$new_pwd<br>$generatePwd<br>$clean_email<br>$sql_upd<br>$new_pwd";
					if($success) 
					{
						
						$time_reset = date("l dS \of F Y h:i:s A");
						$sending = include("app/application/email/email_forgot_password.php");
						//$sending = mail($clean_email,$subject,$body); // sending email
                        if($sending) 
						{
						
						$errormsg[] = "<div class=\"success\">Password Reset! Your new password has been sent to $clean_email <br />Thank you</div>";
						header("refresh:4; url=../../login.php");
                        } 
						else 
						{
                            $errormsg[] = "<div class=\"error\">Couldn't send email. Internal server error! Please contact Information Technology and Innovation Centre(ITIC) @ ".$adminEmail."</div>";
                        }
					}
				} 
		}		
	}
}

?>
<style>
	body {
		font-size:10pt;
		font-family:Geneva,Arial,Helvetica,sans-serif;
		width:100%;
		height:100%;
		}
	#wrapper 
	{
		float:left;
		margin:0 auto;
	}
	.centre {
		margin:0 auto;
		}
	.mainDiv {
		-moz-border-radius:7px;
		-webkit-border-radius:7px;
		/* for Internet Explorer 5.5 - 7 */
		filter: progid:DXImageTransform.Microsoft.gradient(startColorstr=#F2F5F9, endColorstr=#B1B5BA);
		/* for Internet Explorer 8 */
		-ms-filter: "progid:DXImageTransform.Microsoft.gradient(startColorstr=#A2C6F2, endColorstr=#348FDE)";
		/* for Webkit (Safari, Google Chrome, etc) */
		background:-webkit-gradient(linear, left top, left bottom, from(#F2F5F9), to(#B1B5BA));
		/* for mozilla */
		background:-moz-linear-gradient(center top, #F2F5F9, #B1B5BA) scroll 0 0 transparent;
		padding:30px 10px 15px 10px;
		margin:6px;
		float:left;
		/*width:950px;*/
		border:2px solid #68696A;
		border-radius:10px;
    -webkit-border-radius:10px;
    -moz-border-radius:10px;
		}
	.formStyle {
		margin:10px;
	}
	
	.formStyle img {
		margin-top:3px;
		padding:3px;
		background:#FFFFFF;
		border:2px solid #000000;
		-moz-border-radius:3px;
		-webkit-border-radius:3px;
		float:left;
		}
	.formStyle label {
		height:20px;
		width:60px;
		float:left;
		text-align:right;
		padding:7px 10px 5px 7px;
		display:block;
		}
	.formStyle input, textarea, select {
		padding:2px;
		margin:4px;
		}
	.formStyle span {
			color:#999999;
			font-size:10px;
		}
	.result {
		float:left;
		width:40%;
		margin:6px;
		}
	.result ul li {
		list-style:none;
		}
	.result li {
		display:block;
		}
	.messageboxok{
		width:auto;
		/*margin-left:30px;*/
		border:1px solid #349534;
		background:#C9FFCA;
		padding:3px;
		font-weight:bold;
		color:#008000;
		
	}
	.messageboxerror{
		width:auto;
		/*margin-left:30px;*/
		border:1px solid #CC0000;
		background:#F7CBCA;
		padding:3px;
		font-weight:bold;
		color:#CC0000;
	}
  
</style>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $lang; ?>" lang="<?php echo $lang; ?>">

<head>
	<meta http-equiv="content-type" content="text/html; charset=<?php echo $charset; ?>" />
	<meta name="author" content="MJMZ" />

	<title><?php echo load_lang('frame_name'); ?></title>
    <!--<link rel="stylesheet" type="text/css" href="../../theme/css/style.css" media="screen" />-->
	<link rel="stylesheet" type="text/css" href="theme/css/<?php echo $css; ?>" />
	<link rel="stylesheet" type="text/css" href="theme/css/button.css" />
    <!--[if IE 6]><link rel="stylesheet" href="css/ie6.css" type="text/css" media="all" /><![endif]-->
    <script src="js/jquery-1.3.2.min.js" type="text/javascript"></script>
    <script src="js/jquery-fns.js" type="text/javascript"></script>
    <script type="text/javascript" src="lib/js/datePicker/jquery-1.5.1.js"></script>
    <script type="text/javascript" src="lib/js/datePicker/jquery-ui-1.8.11.custom.min.js"></script>
    

<!-- START : put this code below the counting bar -->
<script src="../lib/js/idle/jquery.min.js" type="text/javascript"></script>
<script src="../lib/js/idle/jquery.idletimer.js" type="text/javascript"></script>
<script src="../lib/js/idle/jquery.idletimeout.js" type="text/javascript"></script>

<!--END : put this code below the counting bar -->

<script>
window.onload = firstLoad;
function firstLoad() 
{
	//$(".captcha").load("lib/captcha/captcha.php");
}
function rCaptcha () {
	
	//$(".captcha").load("lib/captcha/captcha.php");
	//$("#captcha1").attr("src", "lib/captcha/captcha.php");
	$("#captcha1").attr("src", "lib/captcha/captcha.php?"+(new Date()).getTime());

}
</script> 
</head>
<body style="width:100%; height:100%;">
<style>

a:hover img {
filter:alpha(opacity=50);
-moz-opacity:0.5;
-khtml-opacity: 0.5;
opacity: 0.5;
}

</style>

		
<div id="wrapper" style="overflow:auto; height:100%; width:100%">
	 <?php
 if(!empty($errormsg)) 
 {
	 foreach($errormsg as $v) 
		echo "  $v\n";
 } 
 ?>

	<div class="mainDiv" style="width:95%;">

	<h4>Forgot Password</h4>
		<form method="post" class="formStyle">
		<table>
			<tr>
				<td><font face="Verdana, Arial, Helvetica, sans-serif">User ID: </font></td>
				<td><input type="text" name="username" id="username" size="32"  /></td>
			</tr>
			<tr>
			<br clear="all" />
				<td><font face="Verdana, Arial, Helvetica, sans-serif">Validation: </font><br clear="all" /></td>
				<td><input class="float-left" type="text" name="validation" size="10" />
				<img id="captcha1" class= "captcha" src="lib/captcha/captcha.php"/>
				<a href="#" class= "transparent" onclick="rCaptcha(); return false;"><img src="theme/images/refresh-1.jpg" width="24px" height="24px" style=" margin-left:5px; padding: 0;border:0px; filter:progid:DXImageTransform.Microsoft.AlphaImageLoader"/></a>
				</td>
			</tr>
			<tr>
			<td></td>
			<td>
			<input type="button" name="back" value="Close" class="btn btn-primary btn-sm" onClick="javascript: parent.$.fn.colorbox.close();"/>
			<input type="submit" name="submit" class="btn btn-primary btn-sm" value="Reset Password"/>
			</td>
			</tr>
		</table>
		</form>
	</div>
</div>

</body>

</html>
