<?php
//**************************************************************************************
// Post Graduate Thesis Monitoring System v1.0.0
// Program Name: pdf_thesis_list.php
//
// Created by: Zuraimi on 01-Jan-2015
// Modified by: Zuraimi on 01-Jan-2015 - Creation of php file
//
//**************************************************************************************
include("../../../lib/common.php");
checkLogin();

//require("../../../lib/fpdf/fpdf.php");
require("../../../lib/fpdf/mc_table_review.php");

$varPrint=isset($_REQUEST["print"])?$_REQUEST["print"]:"";
$varPrintList=isset($_REQUEST["printlist"])?$_REQUEST["printlist"]:"";
$varid=isset($_REQUEST["request_by"])?$_GET["pid"]:"";



$varPrintSplit=array();
//$varColWidth=array();
$strPrint="";
$query_str="";


if(strlen($varPrintList)>0)
{
	$varPrintSplit=explode(",",$varPrintList);
	
	foreach($varPrintSplit as $key => $value)
	{
		$strPrint.=(strlen($strPrint)>0?",":"")."'$value'";
	}
}
$strPrint=(strlen($strPrint)>0?"($strPrint)":$strPrint);

	$varColList=array("No"=>array("width"=>6,"fieldNm"=>""),
					  "Thesis ID "=>array("width"=>20,"fieldNm"=>"id"),
					  "Thesis / Project Title"=>array("width"=>40,"fieldNm"=>"thesis_title"),
					  "Matrix No"=>array("width"=>20,"fieldNm"=>"student_matrix_no"),
					  "Student Name"=>array("width"=>40,"fieldNm"=>"name"),					  
					  "Supervisor Name"=>array("width"=>40,"fieldNm"=>"student_matrix_no"),
					  "Role"=>array("width"=>20,"fieldNm"=>"student_matrix_no"));
					
					
$varColWidth=array(6,20,40,20,40,40,20);

$varDetail=array();

			 
			 
$strSQL="SELECT a.id, b.thesis_title, a.student_matrix_no, c.name
		FROM pg_thesis a
		LEFT JOIN pg_proposal b ON (b.pg_thesis_id = a.id)
		WHERE b.status in ('APP','APC')";
			
$result = $db->query($strSQL);
$studentMatrixNo=$db->f('student_matrix_no');	

$sql1 = "SELECT name
		FROM student
		WHERE matrix_no = '$studentMatrixNo'";		
if (substr($studentMatrixNo,0,2) != '07') { 
	$dbConnStudent= $dbc; 
} 
else { 
	$dbConnStudent=$dbc1; 
}
$result1 = $dbConnStudent->query($sql3); 
$dbConnStudent->next_record();
$studentName=$dbConnStudent->f('name');						
					
						
						
$varDetail2=array();
$varRecCount=0;
$varRecPgCount=0;
$varTempsouvenirCd="";
	while($row = mysql_fetch_array($result)) 
{
	$varRecPgCount=($varTempsouvenirCd!=$row["prf_cd"]?0:$varRecPgCount+1);
	
	$varDetail3Lab["id"]=$row["id"];
	$varDetail3Lab["student_matrix_no"]=$row["student_matrix_no"];
	
	$varFieldCount=0;
		foreach($varColList as $key=>$value)
		{
		$varDetail[$row["id"]][$row["prf_cd"]][$value["fieldNm"]]=$row[$value["fieldNm"]];
		$varDetail[$row["id"]]["title"]=$row["title"];
		
		if($key=="No")
			$varDetail3Tab[$row["prf_cd"]][$varRecCount][$varFieldCount]=$varRecPgCount;
		else
			$varDetail3Tab[$row["prf_cd"]][$varRecCount][$varFieldCount]=$row[$value["fieldNm"]];		
		
		if($key=="No")
			$varDetail2[$varRecCount][$varFieldCount]=$varRecCount;
		else
			$varDetail2[$varRecCount][$varFieldCount]=$row[$value["fieldNm"]];
		
		$varFieldCount++;
		}
	$varTempsouvenirCd=$row["prf_cd"];
	$varRecCount++;
} 

	

class PDF extends FPDF
{
	function Header()
	{		
				
	}

	function Footer()
	{
		$this->SetY(-15);// Position at 1.5 cm from bottom
		$this->SetFont('Arial','I',8);// Arial italic 8

		$this->Ln();
		$this->Cell(0,10,'Page '.$this->PageNo().'',0,0,'L');// Page number
	}
	function Table($col,$data,$varEmpId)
	{
		//Rows
		$this->SetFillColor(224,235,255);
		$this->SetTextColor(0);
		$this->SetFont('');
		$fill=false;
		
		$this->SetLineWidth(.1);
		$this->SetFont('','B');
		$tw=0;
		
		foreach($col as $key=>$value)
		{
			$tw+=$value["width"];
			$this->Cell($value["width"],4,$key,1,0,'L',0);
		}
		$this->Ln();
			
		foreach($data as $key=>$value)
		{
			if(($key!="descriptions")&&($key!="description")&&($key!="title")&&($key!="product_cd"))
			{
				foreach($col as $key1=>$value1)
				{
					$this->Cell($value1["width"],4,$value[$value1["fieldNm"]],1,0,'L',0);
				}
				$this->Ln();
			}
		}
	}
}

$pdf=new PDF_MC_Table_prf("P","mm","letter");


foreach($varDetail3Tab as $key3 => $value3)
{
	$pdf->AddPage();
	$pdf->SetFont('Arial','',10);
	$pdf->Cell(0,10,"As at ".date("d-M-Y"),0,0,"C"); // Title
	//$pdf->Cell(0,10,"List of Post Graduate Thesis / Project for Senate Approval",0,0,"C"); // Title
	$pdf->Ln(2);
	$pdf->SetFont('Arial','',5); 
	$pdf->Text(170,10,"Generated Date : ".date("d-M-Y h:i A"),"R");
	$pdf->Text(170,12,"Generated By     : ".$_SESSION['user_id']);
	$pdf->Text(170,14,"Reference No     : MSU/NT/012014/V1 - 01"); // Title
	$pdf->SetFont('Arial','B',12); // Arial bold 15
	$pdf->Ln(3);
	
	
	// --- TABLE HEADER (START) ---
	$pdf->SetFont('Arial','',7);
	$varLabelLength=18;
	$varValueLength=60;
	$varSpaceLength=25; //ngam2 size



    $pdf->Ln(8);

	
	$pdf->SetLineWidth(.1);
	$pdf->SetFont('','');
	$tw=0;
	foreach($varColList as $key=>$value)
	{
		$tw+=$value["width"];
		$pdf->Cell($value["width"],4,$key,1,0,'C',0);
	}
	$pdf->Ln();
	// --- TABLE HEADER (FINISH) ---
	
	$pdf->SetWidths($varColWidth);
	srand(microtime()*1000000);
	
	foreach($value3 as $key => $value)
	{
		$pdf->Row($value);		
	}
	
	echo $sql2;
	// --- GENERATE SIGNATURE (START) ---		
	$varSignatureHeight=4;
	$pdf->Ln(15);
	$pdf->Cell(0,$varSignatureHeight,'COMMENT PROFESSIONAL : ',0,0,'L');
	$pdf->Ln(4);
	$pdf->Ln(4);
	$pdf->Cell(0,$varSignatureHeight,'.........................................................................',0,0,'L');
	$pdf->Ln(4);
	$pdf->Cell(0,$varSignatureHeight,'.........................................................................',0,0,'L');
	$pdf->Cell(0,$varSignatureHeight,'PROCESSED BY                                                                 ',0,0,'R');
	$pdf->Ln(4);
	$pdf->Cell(0,$varSignatureHeight,'.........................................................................',0,0,'L');
	$pdf->Ln(8);
	$pdf->Cell(0,$varSignatureHeight,'COMMENT PURCHASING ON DISAPPROVED CASES:',0,0,'L');
	$pdf->Cell(0,$varSignatureHeight,'_______________________________________________',0,0,'R');
	$pdf->Ln(6);
	$pdf->Cell(0,$varSignatureHeight,'.........................................................................',0,0,'L');
	$pdf->Cell(0,$varSignatureHeight,'PURCHASING MANAGER                                                  ',0,0,'R');
	$pdf->Ln(4);
	$pdf->Cell(0,$varSignatureHeight,'.........................................................................',0,0,'L');
	$pdf->Ln(4);
	$pdf->Cell(0,$varSignatureHeight,'.........................................................................',0,0,'L');
	$pdf->Cell(0,$varSignatureHeight,'Date:                                                                                     ',0,0,'R');
	$pdf->Ln();
		
		// --- GENERATE SIGNATURE (FINISH) ---
	
	$pdf->SetDisplayMode(100);
}

$pdf->Output();
?>

	

