<?php
require('fpdf.php');
//function hex2dec($couleur = "#000000"){
//    $R = substr($couleur, 1, 2);
//    $rouge = hexdec($R);
//    $V = substr($couleur, 3, 2);
//    $vert = hexdec($V);
//    $B = substr($couleur, 5, 2);
//    $bleu = hexdec($B);
//    $tbl_couleur = array();
//    $tbl_couleur['R']=$rouge;
//    $tbl_couleur['G']=$vert;
//    $tbl_couleur['B']=$bleu;
//    return $tbl_couleur;
//}
//
//conversion pixel -> millimeter at 72 dpi;
//
//function px2mm($px){
//    return $px*25.4/72;
//}

function txtentities($html){
    $trans = get_html_translation_table(HTML_ENTITIES);
    $trans = array_flip($trans);
    return strtr($html, $trans);
}


class PDF_MC_Table_sr2 extends FPDF
{
	var $widths;
	var $aligns;

	function SetWidths($w)
		{
		//Set the array of column widths
		$this->widths=$w;
		}

	function SetAligns($a)
		{
		//Set the array of column alignments
		$this->aligns=$a;
		}


		//$varDetail3Lab[$row["prf_cd"]]["prf_category"]=$row["prf_category"]; 
///////////////////////////////////////////////////////////////////////////////////////////////////
function Header()
	{
		$this->Image("../../../theme/images/msuLogo.gif",20,15,50); // Logo
		$this->Ln(5); 
		$this->SetFont('Arial','B',20); // Arial bold 15
		$this->Cell(245,10,"Management and Science University",0,0,"C"); // Title
		$this->SetFont('Arial','BI',7); // Arial bold 15
		//$this->Cell(260,3,"Generated By: ".$_SESSION['user_id'],0,0,"R"); // Move to the right
		$this->Ln(); 
		$this->Cell(190,20,"Private & Confidential",0,0,'R'); // Reference No
		//$this->Ln(10);
		$this->Ln(12);
		//$this->Cell(0,10,"CATEGORY : TECHNICAL".$varDetail3Lab[$key3]["prf_category"],0,0,"C"); // Title
		//$this->Cell(0,10,"CATEGORY : azni".$_GET["prf_category"],0,0,"C"); // Title	
	}

	// Page footer
	function Footer()
	{
	//	$pdf->SetDash(); //restores no dash
//		$pdf->Line(20,55,190,55);
//		$pdf->Output();
		$this->SetY(-20);// Position at 1.5 cm from bottom
		$this->SetFont('Arial','I',8);// Arial italic 8
		//$this->Cell(0,10,'Page '.$this->PageNo().'/{nb}',0,0,'C');// Page number
		$this->Cell(0,20,"List of Student's Monthly Progress Report",0,0,'L');
		$this->Cell(0,20,'Page '.$this->PageNo().' of {nb}',0,0,'R');// Page number
	}
	
	function Table($col,$data,$varEmpId)
	{
		
		}
		
		
		
function Row($data)
{
	//Calculate the height of the row
	$nb=0;
	for($i=0;$i<count($data);$i++)
		$nb=max($nb,$this->NbLines($this->widths[$i],$data[$i]));

	$h=15*$nb;
	$balance = $nb - 1; //// Calculate balance Line
	if ($balance < 1)
	{
		$h1 = 5.5; // Exact for 3 line sentence . 1 line = 5 height spacing
	}
	else if($balance > 0)
	{
		$h1 = 5.5 + ($balance * 5.5); // Balance line times 5 (line) + with exact for 3 line sentence (15)
	}

	//Issue a page break first if needed
	$this->CheckPageBreak($h1);
	//adjust the table to the left (align)
	$this->Cell(10,4,'',0,0,'L');
	//Draw the cells of the row
	for($i=0;$i<count($data);$i++)
	{
		$w=$this->widths[$i];
		$a=isset($this->aligns[$i]) ? $this->aligns[$i] : 'L';
		//Save the current position
		$x=$this->GetX();
		$y=$this->GetY();
		$yori = $y;
		$yclone = $y +1;
		$yclone1 = $y +6;
		$yclone2 = $y +11;
		//Draw the border
		$this->Rect($x,$y-0.7,$w,$h1); // Draw Table for every row and column

		//Print the text
		$this->MultiCell($w,5,$data[$i],0,$a);

		//Put the position to the right of the cell
		$this->SetXY($x+$w,$y);

		
	}
	//Go to the next line
	$this->Ln($h1);
}
function Row1($data)
{
	//Calculate the height of the row
	$nb=0;
	for($i=0;$i<count($data);$i++)
		$nb=max($nb,$this->NbLines($this->widths[$i],$data[$i]));

	$h=15*$nb;
	$balance = $nb - 1; //// Calculate balance Line
	if ($balance < 1)
	{
		$h1 = 5.5; // Exact for 3 line sentence . 1 line = 5 height spacing
	}
	else if($balance > 0)
	{
		$h1 = 5.5 + ($balance * 5.5); // Balance line times 5 (line) + with exact for 3 line sentence (15)
	}

	//Issue a page break first if needed
	$this->CheckPageBreak($h1);
	//adjust the table to the left (align)
	//$this->Cell(10,4,'',0,0,'L');
	//Draw the cells of the row
	for($i=0;$i<count($data);$i++)
	{
	if ($i==0){
	$this->Cell(10,4,'',0,0,'C');
	$this->SetFont('Arial','B',9);
		$w=$this->widths[$i];
		$a=isset($this->aligns[$i]) ? $this->aligns[$i] : 'L';
		//Save the current position
		$x=$this->GetX();
		$y=$this->GetY();
		$yori = $y;
		$yclone = $y +1;
		$yclone1 = $y +6;
		$yclone2 = $y +11;
		//Draw the border
		$this->Rect($x,$y-0.7,$w,$h1); // Draw Table for every row and column

		//Print the text
		$this->MultiCell($w,5,$data[$i],0,$a);

		//Put the position to the right of the cell
		$this->SetXY($x+$w,$y);

	}
	else{
	$this->SetFont('Arial','',9);
	//$this->Cell(10,4,'',0,0,'C');
		$w=$this->widths[$i];
		$a=isset($this->aligns[$i]) ? $this->aligns[$i] : 'L';
		//Save the current position
		$x=$this->GetX();
		$y=$this->GetY();
		$yori = $y;
		$yclone = $y +1;
		$yclone1 = $y +6;
		$yclone2 = $y +11;
		//Draw the border
		$this->Rect($x,$y-0.7,$w,$h1); // Draw Table for every row and column

		//Print the text
		$this->MultiCell($w,5,$data[$i],0,$a);

		//Put the position to the right of the cell
		$this->SetXY($x+$w,$y);

		}
	}
	//Go to the next line
	$this->Ln($h1);
}

function headRow($data) {
	//Calculate the height of the row
	$nb=0;
	for($i=0;$i<count($data);$i++)
		$nb=max($nb,$this->NbLines($this->widths[$i],$data[$i]));

	$h=15*$nb;
	$balance = $nb - 1; //// Calculate balance Line
	if ($balance < 1)
	{
		$h1 = 5.5; // Exact for 3 line sentence . 1 line = 5 height spacing
	}
	else if($balance > 0)
	{
		$h1 = 5.5 + ($balance * 5.5); // Balance line times 5 (line) + with exact for 3 line sentence (15)
	}
	$this->Cell(10,4,'',0,0,'L');
	$this->SetFont('Arial','B',9);
	for($i=0;$i<count($data);$i++)
	{
		if ($i==0){
		//$this->SetFont('Arial','',9);
			$w=$this->widths[$i];
			$a=isset($this->aligns[$i]) ? $this->aligns[$i] : 'L';
			//Save the current position
			$x=$this->GetX();
			$y=$this->GetY();
			$yori = $y;
			$yclone = $y +1;
			$yclone1 = $y +6;
			$yclone2 = $y +11;
			//Draw the border
			$this->Rect($x,$y-0.7,$w,$h1); // Draw Table for every row and column
	
			//Print the text
			$this->MultiCell($w,5,$data[$i],0,'C');
	
			//Put the position to the right of the cell
			$this->SetXY($x+$w,$y);
	
		}
		else{
		//$this->SetFont('Arial','',9);
		//$this->Cell(10,4,'',0,0,'C');
			$w=$this->widths[$i];
			$a=isset($this->aligns[$i]) ? $this->aligns[$i] : 'L';
			//Save the current position
			$x=$this->GetX();
			$y=$this->GetY();
			$yori = $y;
			$yclone = $y +1;
			$yclone1 = $y +6;
			$yclone2 = $y +11;
			//Draw the border
			$this->Rect($x,$y-0.7,$w,$h1); // Draw Table for every row and column
	
			//Print the text
			$this->MultiCell($w,5,$data[$i],0,$a);
	
			//Put the position to the right of the cell
			$this->SetXY($x+$w,$y);			
			
		}
	}
	$this->Ln($h1);
	$this->SetFont('Arial','',9);
}
function Row2($data, $data2)
{
	//Calculate the height of the row
	$nb=0;
	for($i=0;$i<count($data);$i++)
		$nb=max($nb,$this->NbLines($this->widths[$i],$data[$i]));

	$h=15*$nb;
	$balance = $nb - 1; //// Calculate balance Line
	if ($balance < 1)
	{
		$h1 = 5.5; // Exact for 3 line sentence . 1 line = 5 height spacing
	}
	else if($balance > 0)
	{
		$h1 = 5.5 + ($balance * 5.5); // Balance line times 5 (line) + with exact for 3 line sentence (15)
	}

	//Issue a page break first if needed
	if($this->CheckPageBreak($h1) == "1"){
		$this->headRow($data2);
		
	}
	//adjust the table to the left (align)
	$this->Cell(10,4,'',0,0,'L');
	//Draw the cells of the row
	for($i=0;$i<count($data);$i++)
	{
		if ($i==0){
		//$this->SetFont('Arial','',9);
			$w=$this->widths[$i];
			$a=isset($this->aligns[$i]) ? $this->aligns[$i] : 'L';
			//Save the current position
			$x=$this->GetX();
			$y=$this->GetY();
			$yori = $y;
			$yclone = $y +1;
			$yclone1 = $y +6;
			$yclone2 = $y +11;
			//Draw the border
			$this->Rect($x,$y-0.7,$w,$h1); // Draw Table for every row and column
	
			//Print the text
			$this->MultiCell($w,5,$data[$i],0,'C');
	
			//Put the position to the right of the cell
			$this->SetXY($x+$w,$y);
	
		}
		else{
		//$this->SetFont('Arial','',9);
		//$this->Cell(10,4,'',0,0,'C');
			$w=$this->widths[$i];
			$a=isset($this->aligns[$i]) ? $this->aligns[$i] : 'L';
			//Save the current position
			$x=$this->GetX();
			$y=$this->GetY();
			$yori = $y;
			$yclone = $y +1;
			$yclone1 = $y +6;
			$yclone2 = $y +11;
			//Draw the border
			$this->Rect($x,$y-0.7,$w,$h1); // Draw Table for every row and column
	
			//Print the text
			$this->MultiCell($w,5,$data[$i],0,$a);
	
			//Put the position to the right of the cell
			$this->SetXY($x+$w,$y);			
			
		}
	}
	//Go to the next line
	$this->Ln($h1);
}
function CheckPageBreak($h)
{
	//If the height h would cause an overflow, add a new page immediately
	if($this->GetY()+$h>$this->PageBreakTrigger) {
		$this->AddPage($this->CurOrientation);
		return "1";
	}
}
//variables of html parser
var $B;
var $I;
var $U;
var $HREF;
var $fontList;
var $issetfont;
var $issetcolor;

function PDF($orientation='P', $unit='mm', $format='A4')
{
    //Call parent constructor
    $this->FPDF($orientation,$unit,$format);
    //Initialization
    $this->B=0;
    $this->I=0;
    $this->U=0;
    $this->HREF='';
	
	$this->tableborder=0;
    $this->tdbegin=false;
    $this->tdwidth=0;
    $this->tdheight=0;
    $this->tdalign="L";
    $this->tdbgcolor=false;
	
	$this->oldx=0;
    $this->oldy=0;
	
    $this->fontlist=array('arial', 'times', 'courier', 'helvetica', 'symbol');
    $this->issetfont=false;
    $this->issetcolor=false;
}

function WriteHTML($html)
{
	
    $html=strip_tags($html,"<b><u><i><a><img><p><br><strong><em><font><tr><blockquote><hr><td><tr><table><sup>"); //remove all unsupported tags
    $html=str_replace("\n",'',$html); //replace carriage returns by spaces
    $html=str_replace("\t",'',$html); //replace carriage returns by spaces
    $a=preg_split('/<(.*)>/U',$html,-1,PREG_SPLIT_DELIM_CAPTURE); //explodes the string
    foreach($a as $i=>$e)
    {
        if($i%2==0)
        {
            //Text
            if($this->HREF)
                $this->PutLink($this->HREF,$e);
            elseif($this->tdbegin) {
                if(trim($e)!='' && $e!="&nbsp;") {
                    $this->Cell($this->tdwidth,$this->tdheight,$e,$this->tableborder,'',$this->tdalign,$this->tdbgcolor);
                }
                elseif($e=="&nbsp;") {
                    $this->Cell($this->tdwidth,$this->tdheight,'',$this->tableborder,'',$this->tdalign,$this->tdbgcolor);
                }
            }
            else
                $this->Write(5,stripslashes(txtentities($e)));
        }
        else
        {
            //Tag
            if($e[0]=='/')
                $this->CloseTag(strtoupper(substr($e,1)));
            else
            {
                //Extract attributes
                $a2=explode(' ',$e);
                $tag=strtoupper(array_shift($a2));
                $attr=array();
                foreach($a2 as $v)
                {
                    if(preg_match('/([^=]*)=["\']?([^"\']*)/',$v,$a3))
                        $attr[strtoupper($a3[1])]=$a3[2];
                }
                $this->OpenTag($tag,$attr);
            }
        }
    }
}

function OpenTag($tag, $attr)
{	
    //Opening tag
    switch($tag){
	
		 case 'SUP':
            if( !empty($attr['SUP']) ) {    
                //Set current font to 6pt     
                $this->SetFont('','',6);
                //Start 125cm plus width of cell to the right of left margin         
                //Superscript "1" 
                $this->Cell(2,2,$attr['SUP'],0,0,'L');
            }
            break;
			
		case 'TABLE': // TABLE-BEGIN
            if( !empty($attr['BORDER']) ) $this->tableborder=$attr['BORDER'];
            else $this->tableborder=0;
            break;
			
        case 'TR': //TR-BEGIN
            break;
			
        case 'TD': // TD-BEGIN
            if( !empty($attr['WIDTH']) ) $this->tdwidth=($attr['WIDTH']/4);
            else $this->tdwidth=40; // Set to your own width if you need bigger fixed cells
            if( !empty($attr['HEIGHT']) ) $this->tdheight=($attr['HEIGHT']/6);
            else $this->tdheight=6; // Set to your own height if you need bigger fixed cells
            if( !empty($attr['ALIGN']) ) {
                $align=$attr['ALIGN'];        
                if($align=='LEFT') $this->tdalign='L';
                if($align=='CENTER') $this->tdalign='C';
                if($align=='RIGHT') $this->tdalign='R';
            }
            else $this->tdalign='L'; // Set to your own
            if( !empty($attr['BGCOLOR']) ) {
                $coul=hex2dec($attr['BGCOLOR']);
                    $this->SetFillColor($coul['R'],$coul['G'],$coul['B']);
                    $this->tdbgcolor=true;
                }
            $this->tdbegin=true;
            break;

        case 'HR':
            if( !empty($attr['WIDTH']) )
                $Width = $attr['WIDTH'];
            else
                $Width = $this->w - $this->lMargin-$this->rMargin;
            $x = $this->GetX();
            $y = $this->GetY();
            $this->SetLineWidth(0.2);
            $this->Line($x,$y,$x+$Width,$y);
            $this->SetLineWidth(0.2);
            $this->Ln(1);
            break;
			
        case 'STRONG':
            $this->SetStyle('B',true);
            break;
        case 'EM':
            $this->SetStyle('I',true);
            break;
        case 'B':
        case 'I':
        case 'U':
            $this->SetStyle($tag,true);
            break;
        case 'A':
            $this->HREF=$attr['HREF'];
            break;
        case 'IMG':
            if(isset($attr['SRC']) && (isset($attr['WIDTH']) || isset($attr['HEIGHT']))) {
                if(!isset($attr['WIDTH']))
                    $attr['WIDTH'] = 0;
                if(!isset($attr['HEIGHT']))
                    $attr['HEIGHT'] = 0;
                $this->Image($attr['SRC'], $this->GetX(), $this->GetY(), px2mm($attr['WIDTH']), px2mm($attr['HEIGHT']));
            }
            break;
      
        case 'BLOCKQUOTE':
        case 'BR':
            $this->Ln(5);
            break;
        case 'P':
            $this->Ln(5);
            break;
        case 'FONT':
            if (isset($attr['COLOR']) && $attr['COLOR']!='') {
                $coul=hex2dec($attr['COLOR']);
                $this->SetTextColor($coul['R'],$coul['V'],$coul['B']);
                $this->issetcolor=true;
            }
            if (isset($attr['FACE']) && in_array(strtolower($attr['FACE']), $this->fontlist)) {
                $this->SetFont(strtolower($attr['FACE']));
                $this->issetfont=true;
            }
            break;
    }
}

function CloseTag($tag)
{	
    //Closing tag
	
	if($tag=='SUP') {
    }

    if($tag=='TD') { // TD-END
        $this->tdbegin=false;
        $this->tdwidth=0;
        $this->tdheight=0;
        $this->tdalign="L";
        $this->tdbgcolor=false;
    }
    if($tag=='TR') { // TR-END
        $this->Ln();
    }
    if($tag=='TABLE') { // TABLE-END
        //$this->Ln();
        $this->tableborder=0;
    }
	
    if($tag=='STRONG')
        $tag='B';
    if($tag=='EM')
        $tag='I';
    if($tag=='B' || $tag=='I' || $tag=='U')
        $this->SetStyle($tag,false);
    if($tag=='A')
        $this->HREF='';
    if($tag=='FONT'){
        if ($this->issetcolor==true) {
            $this->SetTextColor(0);
        }
        if ($this->issetfont) {
            $this->SetFont('arial');
            $this->issetfont=false;
        }
    }
}

function SetStyle($tag, $enable)
{	$pdf->SetX (20);
    //Modify style and select corresponding font
    $this->$tag+=($enable ? 1 : -1);
    $style='';
    foreach(array('B','I','U') as $s)
    {
        if($this->$s>0)
            $style.=$s;
    }
    $this->SetFont('',$style);
}

function PutLink($URL, $txt)
{	$pdf->SetX (20);
    //Put a hyperlink
    $this->SetTextColor(0,0,255);
    $this->SetStyle('U',true);
    $this->Write(5,$txt,$URL);
    $this->SetStyle('U',false);
    $this->SetTextColor(0);
}
function NbLines($w,$txt)
{	
	//Computes the number of lines a MultiCell of width w will take
	$cw=&$this->CurrentFont['cw'];
	if($w==0)
		$w=$this->w-$this->rMargin-$this->x;
	$wmax=($w-2*$this->cMargin)*1000/$this->FontSize;
	$s=str_replace("\r",'',$txt);
	$nb=strlen($s);
	if($nb>0 and $s[$nb-1]=="\n")
		$nb--;
	$sep=-1;
	$i=0;
	$j=0;
	$l=0;
	$nl=1;
	while($i<$nb)
	{
		$c=$s[$i];
		if($c=="\n")
		{
			$i++;
			$sep=-1;
			$j=$i;
			$l=0;
			$nl++;
			continue;
		}
		if($c==' ')
			$sep=$i;
		$l+=$cw[$c];
		if($l>$wmax)
		{
			if($sep==-1)
			{
				if($i==$j)
					$i++;
			}
			else
				$i=$sep+1;
			$sep=-1;
			$j=$i;
			$l=0;
			$nl++;
		}
		else
			$i++;
	}
	return $nl;
}
}
?>
